### ISSUE TITLE
There is some error.

### ISSUE THREAD

**Issue by cfcayan** [shikhar1sharma/facebook-scraping-selenium#1]
Traceback (most recent call last):
  File "facebook_posts.py", line 242, in <module>
    result = fb_dump_posts(browser)
  File "facebook_posts.py", line 170, in fb_dump_posts
    posts = driver.find_elements_by_class_name(post_class)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 438, in find_elements_by_class_name
    return self.find_elements(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 810, in find_elements
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: Compound class names not permitted
  (Session info: headless chrome=70.0.3538.77)
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.15.0-36-generic x86_64)

**Comment by shikhar1sharma** [comment]
Can you tell me more about the environment which you are running it on?
Check the chrome and linux version.

**Comment by cfcayan** [comment]
Ubuntu 18.10 and Chromium 70
